name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1
environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_forms: ^1.0.1-alpha
  angular_router: ^2.0.0-alpha

dev_dependencies:
  angular_test: ^1.0.2-alpha
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  mockito: ^2.0.2
  test: ^0.12.21

dependency_overrides:
  angular: ^5.0.0-alpha

transformers:
- angular:
    entry_points:
    - web/main.dart
    - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
