name: api_docs
description: >
  Pubspec used to fetch specific versions of packages for the purpose of generating API docs,
  and for checking if new versions are available (see gulp/pkg-vers.js).
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+1
  angular_components: ^0.9.0-alpha+1
  angular_forms: ^1.0.1-alpha+1
  angular_router: ^2.0.0-alpha+1
  angular_test: ^1.0.2-alpha+1

dependency_overrides:
  analyzer: ^0.31.0-alpha.1
  angular_components:
    git:
      url: https://github.com/dart-lang/angular_components.git
      ref: github-sync
