# #docplaster
name: router_example
description: Router Example
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

# #docregion dependencies, dependencies-wo-forms
dependencies:
  angular: ^5.0.0-alpha
  # #enddocregion dependencies-wo-forms
  angular_forms: ^1.0.1-alpha
  # #docregion dependencies-wo-forms
  angular_router: ^2.0.0-alpha
# #enddocregion dependencies, dependencies-wo-forms

dependency_overrides:
  angular: ^5.0.0-alpha

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
